Document: eatmysoul
Title: Debian eatmysoul Manual
Author: <insert document author here>
Abstract: This manual describes what eatmysoul is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eatmysoul/eatmysoul.sgml.gz

Format: postscript
Files: /usr/share/doc/eatmysoul/eatmysoul.ps.gz

Format: text
Files: /usr/share/doc/eatmysoul/eatmysoul.text.gz

Format: HTML
Index: /usr/share/doc/eatmysoul/html/index.html
Files: /usr/share/doc/eatmysoul/html/*.html
